name: Test Website

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Get project files
        uses: actions/checkout@v4

      - name: Show HTML
        run: type index.html

      - name: Show CSS
        run: type style.css

      - name: Show JavaScript
        run: type script.js